### PR TITLE
qmk: Update python resources and rebuild for 3.11

### PR DESCRIPTION
**Pull request by fauxpark**
## Description

#48

### CODE REVIEW

**Review by zvecr — APPROVED** [review]

**Comment by fauxpark** [comment]
It's not building the bottle...

**Comment by fauxpark** [comment]
Looks like the GHA runner needs to be updated, [Homebrew's minimum version is now 11](https://docs.brew.sh/Installation#macos-requirements) and [the 10.15 runner is deprecated](https://github.com/actions/runner-images#available-images).

**Comment by fauxpark** [comment]
Didn't work. Not sure which formula it's complaining about then...

**Comment by fauxpark** [comment]
```
$ brew unbottled qmk
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Populating dependency tree...
==> :ventura bottle status
qmk: unbottled deps: mdloader arm-gcc-bin@8 avr-binutils avr-gcc@8
```
????

**Comment by fauxpark** [comment]
Ah, for 11 it's just mdloader. Found the smoking gun.

**Pull request closed without merging**
